@echo off
REM Paper + Geyser Setup Script (Windows)
REM This script downloads and configures Paper server with Geyser plugin

setlocal enabledelayedexpansion

set "PAPER_VERSION=1.21.1"
set "PAPER_BUILD=latest"
set "GEYSER_VERSION=latest"

set "SCRIPT_DIR=%~dp0"
set "SERVER_DIR=%SCRIPT_DIR%paper-server"
set "PLUGINS_DIR=%SERVER_DIR%\plugins"

echo =========================================
echo Paper + Geyser Setup Script (Windows)
echo =========================================
echo Minecraft Version: %PAPER_VERSION%
echo Server Directory: %SERVER_DIR%
echo.

REM Create directories
if not exist "%SERVER_DIR%" mkdir "%SERVER_DIR%"
if not exist "%PLUGINS_DIR%" mkdir "%PLUGINS_DIR%"

cd /d "%SERVER_DIR%"

REM Download Paper if not exists
if not exist "paper.jar" (
    echo Downloading Paper %PAPER_VERSION%...
    echo.
    echo Note: Download requires curl. If this fails, manually download from:
    echo https://papermc.io/downloads
    echo.

    REM Try to download Paper
    curl -o paper.jar -L "https://api.papermc.io/v2/projects/paper/versions/%PAPER_VERSION%/builds/latest/downloads/paper-%PAPER_VERSION%-latest.jar" 2>nul

    if errorlevel 1 (
        echo.
        echo Error: Failed to download Paper automatically.
        echo.
        echo Please manually download Paper from:
        echo   https://papermc.io/downloads
        echo.
        echo Download the JAR for version %PAPER_VERSION% and place it as:
        echo   %SERVER_DIR%\paper.jar
        echo.
        echo Then run this script again.
        pause
        exit /b 1
    )

    echo [OK] Paper downloaded successfully
) else (
    echo [OK] Paper server already exists (paper.jar^)
)

REM Download Geyser if not exists
if not exist "%PLUGINS_DIR%\Geyser-Spigot.jar" (
    echo.
    echo Downloading Geyser plugin...

    cd /d "%PLUGINS_DIR%"

    curl -o Geyser-Spigot.jar -L "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot" 2>nul

    if errorlevel 1 (
        echo.
        echo Error: Failed to download Geyser automatically.
        echo.
        echo Please manually download Geyser from:
        echo   https://geysermc.org/download
        echo.
        echo Download "Geyser-Spigot" and place it as:
        echo   %PLUGINS_DIR%\Geyser-Spigot.jar
        echo.
        echo Then run this script again.
        cd /d "%SERVER_DIR%"
        pause
        exit /b 1
    )

    echo [OK] Geyser downloaded successfully
) else (
    echo [OK] Geyser plugin already exists
)

cd /d "%SERVER_DIR%"

REM Create eula.txt
if not exist "eula.txt" (
    echo.
    echo Creating eula.txt (you are agreeing to Minecraft's EULA^)...
    echo # By changing the setting below to TRUE you are indicating your agreement to Minecraft's EULA (https://aka.ms/MinecraftEULA^). > eula.txt
    echo eula=true >> eula.txt
    echo [OK] EULA accepted
)

REM Create server.properties with RCON enabled
if not exist "server.properties" (
    echo.
    echo Creating server.properties with RCON enabled...
    (
        echo # Minecraft server properties
        echo # Generated by FGD setup script
        echo.
        echo # Server Settings
        echo server-port=25565
        echo server-ip=
        echo max-players=20
        echo motd=FGD AICraft Server - Paper + Geyser
        echo online-mode=false
        echo allow-flight=true
        echo difficulty=normal
        echo gamemode=survival
        echo pvp=true
        echo.
        echo # RCON Configuration (Required for FGD Dashboard^)
        echo enable-rcon=true
        echo rcon.port=25575
        echo rcon.password=fgd_rcon_password_change_me
        echo broadcast-rcon-to-ops=true
        echo.
        echo # World Settings
        echo level-name=world
        echo level-seed=
        echo level-type=minecraft\:normal
        echo spawn-protection=16
        echo view-distance=10
        echo simulation-distance=10
        echo.
        echo # Performance
        echo max-tick-time=60000
        echo network-compression-threshold=256
        echo sync-chunk-writes=true
        echo.
        echo # Other
        echo white-list=false
        echo enforce-whitelist=false
        echo spawn-npcs=true
        echo spawn-animals=true
        echo spawn-monsters=true
        echo generate-structures=true
    ) > server.properties
    echo [OK] server.properties created
    echo   RCON Port: 25575
    echo   RCON Password: fgd_rcon_password_change_me
    echo   WARNING: IMPORTANT: Change the RCON password in server.properties!
)

REM Create start script
echo.
echo Creating start script...
(
    echo @echo off
    echo REM Paper Server Start Script
    echo REM Adjust memory settings based on your system
    echo.
    echo set "SCRIPT_DIR=%%~dp0"
    echo cd /d "%%SCRIPT_DIR%%"
    echo.
    echo REM Memory settings (adjust as needed^)
    echo set "MIN_RAM=2G"
    echo set "MAX_RAM=4G"
    echo.
    echo REM Java arguments for performance
    echo set "JAVA_ARGS=-Xms%%MIN_RAM%% -Xmx%%MAX_RAM%% -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
    echo.
    echo echo Starting Paper server...
    echo echo Memory: %%MIN_RAM%% - %%MAX_RAM%%
    echo echo.
    echo.
    echo java %%JAVA_ARGS%% -jar paper.jar --nogui
    echo.
    echo echo.
    echo echo Server stopped.
    echo pause
) > start.bat

echo [OK] Start script created (start.bat^)

echo.
echo =========================================
echo Setup Complete!
echo =========================================
echo.
echo Next Steps:
echo 1. Edit server.properties and change RCON password
echo 2. Configure Geyser in plugins\Geyser-Spigot\config.yml (after first run^)
echo 3. Update FGD minecraft-bridge-config.js with RCON credentials
echo 4. Start the Paper server: cd minecraft-servers\paper-server ^&^& start.bat
echo 5. Start the FGD dashboard: start-server.bat
echo.
echo Server Ports:
echo   - Java Edition: 25565
echo   - Bedrock Edition: 19132 (UDP, configured in Geyser^)
echo   - RCON: 25575
echo   - FGD Dashboard: 3000
echo.
echo WARNING: IMPORTANT:
echo   - Change RCON password in server.properties
echo   - Configure Geyser settings after first server start
echo   - Open ports in Windows Firewall if needed
echo.
pause
